### ISSUE TITLE
[fix]하트두번, 신고하기 두번 누르면 alert창 뜨는거 => toast메세지로 변경요청

### ISSUE THREAD

**Issue by rud1676** [project-GAZA/GazaFront#26]
### Description

<img width="174" alt="image" src="https://github.com/project-GAZA/GazaFront/assets/51875363/8da33143-7a14-42b3-96c6-62a4a4b9da77">

해당 부분 하트는 두번 안눌리게(두번누르면 alert창으로 경고뜸) 신고하기도 두번 안눌리게(alert창으로 경고뜸)

useCustomToast를 사용해서 toast메세지로 바꿔주세요!!

### In Progress

> 작업사항들을 작성해주세요.

- [x] alert창 toast로 변경해주세요
- [x] CommentComponent 변경하기

**Comment by osohyun0224** [comment]
확인했습니다!
