### ISSUE TITLE
[Feat] Mobile버전에도 메뉴부분 적용해주세요!

### ISSUE THREAD

**Issue by rud1676** [project-GAZA/GazaFront#34]
### Description

> figma 메뉴 디자인을 모바일 버전도 적용해주세요!

### In ScreenShot

<img width="671" alt="image" src="https://github.com/project-GAZA/GazaFront/assets/51875363/cb391375-5f31-4b45-818b-41c0f11325bd">

**Comment by osohyun0224** [comment]
이슈 반영으로 인해 닫겠습니다!
