### ISSUE TITLE
[BUG] NEW 버튼 동작 안 합니다!

### ISSUE THREAD

**Issue by jangseoyoung98** [project-GAZA/GazaFront#40]
### Describe the bug

> section3에서 new 버튼 눌렀을 때, 메시지들이 안 뜨고 있습니다!

### To Reproduce

> 버그 발생 과정을 기술하세요.

- 화면 처음 접속하고, new 버튼 눌렀을 때 안 나옵니다.
- 새로 고침 했을 때도, 안 나옵니다.

### Screenshots

> 화면 첨부파일
![image](https://github.com/project-GAZA/GazaFront/assets/77472570/b1d30949-5a44-40eb-bc19-c9e31bfe0060)

**Comment by rud1676** [comment]
@osohyun0224 체크한번 부탁드립니다! -> api수정작업이 있었는데(수정후 복구했습니다) postman으로 먼저 테스트해보고
진행 부탁드립니다!

**Comment by osohyun0224** [comment]
이슈 반영으로 인해 닫겠습니다!
