### ISSUE TITLE
[BUG]Build시에 type에러 나는 것 수정한번 부탁드립니다!!

### ISSUE THREAD

**Issue by rud1676** [project-GAZA/GazaFront#44]
### Describe the bug

무한 스크롤 구현시 

build시에 타입스크립트 type에러가 뜹니다.!!

급하게 임시로 배포해야될 상황이 와서 tsconfig의 strick을 false로 하고 배포가 진행된 상황인데,

수정 완료되면 strick:true로 변경하고 PR부탁드리겠습니다!!

### Screenshots

<img width="608" alt="image" src="https://github.com/project-GAZA/GazaFront/assets/51875363/3672f55c-8df5-4698-b3a5-4d333a8f7b50">

### Additional context(Optional)

> 문제가 있는 부분은 Comment에 언급해주세요!!

**Comment by osohyun0224** [comment]
이슈 해결으로 인해 해당 이슈 닫겠습니다!
